# Generated by Django 6.0.3 on 2026-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PacketEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("packet_one_kg", models.IntegerField()),
                ("packet_half_kg", models.IntegerField()),
                ("price_one_kg", models.IntegerField()),
                ("price_half_kg", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
