# Generated by Django 6.0.3 on 2026-03-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packetentry",
            name="packet_half_kg",
            field=models.IntegerField(verbose_name="Half KG Packets"),
        ),
        migrations.AlterField(
            model_name="packetentry",
            name="packet_one_kg",
            field=models.IntegerField(verbose_name="One KG Packets"),
        ),
        migrations.AlterField(
            model_name="packetentry",
            name="price_half_kg",
            field=models.IntegerField(verbose_name="Half KG Price"),
        ),
        migrations.AlterField(
            model_name="packetentry",
            name="price_one_kg",
            field=models.IntegerField(verbose_name="One KG Price"),
        ),
    ]
